### ISSUE TITLE
Incremental EM

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#225]
Working on the spam filter application, I'm seeing that what we really need is a way to learn from emails in real time as they arrive. An incremental EM algorithm will provide that.

**Comment by mhoward2718** [comment]
I have been looking at this issue this morning.

It isn't hard to make a version of EM that can be stopped and restarted. For the first cut, I just overrode the 'doStart' method to not throw an exception if the algorithm had already been run before. More realistically, maybe we would use an 'update' method or something similar.

But this example program starts to run low on memory after only a few hundred iterations of the while loop. It seems that this issue might be less about the algorithm itself and more about providing a way to allow elements to be garbage collected without forgetting the effect of their observation on the parameter. 

```scala
val trueAlpha = 2.0
  val trueBeta = 4.0
  val distribution = new org.apache.commons.math3.distribution.BetaDistribution(trueAlpha,trueBeta)
  
  def nextOutcome(): Boolean = {
    val prob = distribution.sample()
    if (prob > 0.50) true else false
  }
  
  def main(args: Array[String]) = {
    val p = Beta(12.0,4.0)
    
    val algorithm = EMWithVE.online(10,p)
    while (true) {

      println(p.MAPValue + " " + p.learnedAlpha + " " + p.learnedBeta)
      val next = nextOutcome()
      Flip(p).observe(next)
      algorithm.start()
      algorithm.stop()

    }
    algorithm.kill()
  }
```

**Comment by gtakata** [comment]
Can you explain why the memory is growing? Typically EM  has only short-term memory. Once you calculate the E from the data and the M from the E, you “forget” the previous potentials and use the new ones. The memory should stabilize after a few iterations even tho the potentials keep changing (hopefully converging)

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by mhoward2718** [comment]
It was a little inaccurate to say that the program was low on memory. But it does run noticeably slower. The reason is that a new Flip is created in each iteration of the while loop. Now, what we'd usually do in a situation where we have so many Flips is replace them with a single Binomial. But we can't do that in this setting. As we create more and more elements, the inference algorithm we use in the E step becomes slower.

**Comment by gtakata** [comment]
If you are creating new Elements, presumably because you can’t just change the potentials on the existing ones, then the old ones should be obsolete. So why are they kept around and why are they still used in the next E calculation?

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>
