### ISSUE TITLE
Bug in VETest

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#404]
The test "with a constraint on an element that is used multiple times, only factor in the constraint once" in VETest passes consistently when you run it on its own, but fails consistently when you run the entire suite. There are also some tests in BPTest that are similarly failing when you run the suite, but I wasn't able to run them individually to see if they pass then.

This may have to do with the recent factor fix #402.

**Comment by bruttenberg** [comment]
Hi Avi,

Glenn is aware of the problem on this bug and is trying to fix it.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by gtakata** [comment]
It was happening before fix #402. The fix only made it go from random to consistent.

All fix 402 did was to deduplicate before taking a product so that the product can be taken in either order. This should not be affected by previous tests since it relies only on the factors in question.

One possibility is that there is some kind of contamination from previous tests. Some candidates are:

1)      New universe not being used, even tho created in each test

2)      Leftover state somewhere. Does VE cache or preserve state between invocations?

3)      Threading issues. For instance, does Universe.createNew() complete before the new Elements are being created (if not an existing universe may be used instead)

This might, in fact, affect the deduplication since Variable relies on the universe associated with the Element and deduplication relies on this range.


*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by bruttenberg** [comment]
Glenn, the vetest avi is referring to is the problem you are debugging, correct? That is the test I looked at that had the problem when the same variable is used twice in a factor.


Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------
From: Glenn Takata
Date:03/23/2015 7:45 AM (GMT-05:00)
To: p2t2/figaro
Cc: Brian Ruttenberg
Subject: Re: [figaro] Bug in VETest (#404)

It was happening before fix #402. The fix only made it go from random to consistent.

All fix 402 did was to deduplicate before taking a product so that the product can be taken in either order. This should not be affected by previous tests since it relies only on the factors in question.

One possibility is that there is some kind of contamination from previous tests. Some candidates are:

1) New universe not being used, even tho created in each test

2) Leftover state somewhere. Does VE cache or preserve state between invocations?

3) Threading issues. For instance, does Universe.createNew() complete before the new Elements are being created (if not an existing universe may be used instead)

This might, in fact, affect the deduplication since Variable relies on the universe associated with the Element and deduplication relies on this range.


*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by gtakata** [comment]
Yup.

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>
