### ISSUE TITLE
Bug in MH initialization - setting elements to their observed values

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#453]
When MH is initialized, elements that are observed are set to their observed value. This is problematic when the observation is a deterministic function of other elements. If the observed value is inconsistent with the values of those elements, the following can happen.
1. At some point, some other elements will be proposed that don't affect this observed element. In that case, the proposal might be accepted.
2. Once any proposal has been accepted, only proposals that satisfy all the conditions can be accepted.
3. As a result, any change to the elements that affect this observed element will be rejected, unless that change actually leads to the observation being satisfied. This is even if it is a "good" change that leads it closer to being satisfied.

An example of this is the SimpleMovie example. The current code usually works because the number of appearances is small, so the number of awarded appearances is almost always 0 or 1 at first. Therefore, it can quickly reach the observed value of 1. (However, this bug might explain why this test occasionally fails.)

However, if you increase the number of appearances so that many would be awarded without the constraint (say 5), the proposal scheme says to remove one award (making the value 4). Unfortunately, this is always rejected, so the sampler makes no progress.

**Comment by bruttenberg** [comment]
Avi, we need to talk about this. This was changed a couple of weeks ago because it was actually (incorrectly) recording values of proposals that led to an inconsistent state. This is different than accepting proposals that improve the state of the model, but NOT recording the values as samples. We can talk tomorrow.



+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>
