### ISSUE TITLE
FairDice example won't compile

### ISSUE THREAD

**Issue by d10genes** [p2t2/figaro#513]
Appears to be failing on [this line](https://github.com/p2t2/figaro/blob/2687f155c94c77eca9e57a2d6031784ade3977d6/FigaroExamples/src/main/scala/com/cra/figaro/example/FairDice.scala#L92):

```
Error:(97, 29) lazy value probs in class Select cannot be accessed in com.cra.figaro.language.Select[Double,Int] with com.cra.figaro.language.HasDensity[Int]
    val probsAndSides1 = d1.probs zip outcomes
                            ^
```

I installed Figaro with
```
name := "fig"
version := "1.1"
scalaVersion := "2.11.6"
libraryDependencies += "com.cra.figaro" %% "figaro" % "3.3.0.0"
```
which I believe is the latest release (couldn't find an updated quickstart with install instructions).

**Comment by mreposa** [comment]
Hello and thank you for your interest in Figaro!

Unfortunately, I cannot reproduce the problem you're experiencing. I have compiled the examples under both the DEV3.3 branch and "master" branch and the examples compiled on both.

It’s possible it’s a scoping issue. The FairDice example has this line:

     val probsAndSides1 = d1.probs zip outcomes

but d1.probs is declared as private[Figaro]. Is it possible you might have changed the package of the example in the source file? If this is the case, it wouldn’t compile due to the private variable.

**Comment by d10genes** [comment]
Yes, that's what happened, I tried copy/pasting into a new file since I couldn't find the examples with the figaro installation. Thanks!
