### ISSUE TITLE
Building factors can be very slow

### ISSUE THREAD

**Issue by mhoward2718** [p2t2/figaro#531]
Factor creation time can be extremely slow in models with a large number of elements. From profiling, the creation time is dominated by computing hash codes of caches in universe.register. Each time an element is added to a cache, the cache itself is re-registered with the universe. Worse, the hashcodes for maps are computed from their contents, which means that computing the hashcode becomes slower as the map grows.

For example, in ```Variable.scala```, we have:

```scala
  private def make[T](elem: Element[T]): Variable[T] = {
    // Make sure that the element will be removed from the memoMake map when it is inactivated
    elem.universe.register(memoMake)
    elem.universe.register(idCache)
    new ElementVariable(elem)
  }
```

It is unnecessary to call register with ```memoMake``` and ```idCache``` in each call to ```make```, and it can really slow down factor creation in large models. The same pattern occurs in places like ```Factory```, with ```factorCache```.

Some possible solutions would be:

A) Explicitly register caches with a universe at the beginning of factor creation.

B) Manually override the hashcode of caches inside objects like ```Variable``` and ```Factory```.

C) Use a data structure that doesn't compare hashcodes like ```List``` instead of ```Set``` for Universe.registeredMaps.

**Comment by bruttenberg** [comment]
Thanks Michael. Actually, since I’m merging the SFI factor creation into the main code base, this might change and I’ll be sure to make sure that this changes to one of your suggestions.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>
