### ISSUE TITLE
Metropolis-Hastings may not converge to target distribution

### ISSUE THREAD

**Issue by yfcai** [p2t2/figaro#548]
Figaro Tutorial §5.7.2, paragraph 1 describes the transition of Figaro's Metropolis-Hastings algorithm as follows.

> Chains contain an internal cache of previously generated elements from different combinations of its argument values. When a chain's function is invoked on an argument to produce a result element, the cache is first checked to determine if there exists an entry for the argument value. If an entry does exist, the cached element is retrieved and used to determine the value of the chain... once the capacity of the cache is reached, **a random element** is selected and discarded.

A program may have multiple regions of accepting states reachable from one another only by re-sampling more than one element. When that happens, the MH chain gets stuck inside one region and does not compute the correct probabilities. Here is an example in pseudocode and Figaro.

```haskell
do
  x <- flip 0.5
  y <- flip 0.5
  observe (xor x y)
  return y
```

```scala
import com.cra.figaro.language._
import com.cra.figaro.algorithm.sampling._

object Test extends App {
  val X = Flip(0.5)
  val Y = Flip(0.5)
  val Z = for { x <- X ; y <- Y } yield x ^ y

  Z.setCondition(z => z)

  val mh = MetropolisHastings(5000, ProposalScheme.default, Y)

  mh.start()

  println(s"Pr[Y = true  | X xor Y = true] = ${mh.probability(Y, true )}")
  println(s"Pr[Y = false | X xor Y = true] = ${mh.probability(Y, false)}")
}
```

Intuitively, `Pr[Y = true | xor X Y = true] = 0.5`. This program has two accepting states, `[X = true, Y = false]` and `[X = false, Y = true]`. Since it's not possible to transition from one to the other by re-sampling one element, the chain gets stuck in the first accepting state forever.

```
> run
[info] Running Test 
Pr[Y = true  | X xor Y = true] = 0.0
Pr[Y = false | X xor Y = true] = 1.0
[success] Total time: 1 s, completed Feb 5, 2016 7:17:26 PM
> run
[info] Running Test 
Pr[Y = true  | X xor Y = true] = 0.0
Pr[Y = false | X xor Y = true] = 1.0
[success] Total time: 0 s, completed Feb 5, 2016 7:17:31 PM
> run
[info] Running Test 
Pr[Y = true  | X xor Y = true] = 1.0
Pr[Y = false | X xor Y = true] = 0.0
[success] Total time: 0 s, completed Feb 5, 2016 7:17:40 PM
```

**Comment by bruttenberg** [comment]
Hi Cai,

Thanks for giving Figaro a try and thanks for the email!

I think what you’re pointing out is not really a limitation of Figaro. Rather, it is a limitation of a single proposal MH algorithm.

As you note, you can certainly code a model in Figaro where it is not possible to reach an accepting state of MH with a single change in the model – it has certainly happened to us with own models sometimes. The issue here really is that one needs to design a proposal scheme that will proposal intelligently on the model.

Figaro provides the basic ProposalScheme.default which just selects since change proposals, which in this case does not work. For example, if I make this change to your model:

  val scheme = ProposalScheme(X, Y)
  val mh = MetropolisHastings(5000, scheme, Y)

I get this output:

Pr[Y = true  | X xor Y = true] = 0.5134
Pr[Y = false | X xor Y = true] = 0.4866

Does that make sense?

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by yfcai** [comment]
Hi Brian, thanks for your answer. I couldn't tell from the tutorial alone that a proposal scheme can update multiple elements at once.
