### ISSUE TITLE
Inconsistencies in several factor operations

### ISSUE THREAD

**Issue by wkretschmer** [p2t2/figaro#588]
`Factor.marginalizeTo` completely ignores the semiring given, since the only implementation of this method in `BasicFactor` uses the semiring in the constructor. Nevertheless, current use of the method suggests this is not intended. Consider the following code from `LazyVariableElimination.scala`:
```
private def marginalizeToTarget(factor: Factor[(Double, Double)], target: Element[_]): Unit = {
  val targetFactor = factor.marginalizeTo(BoundsSumProductSemiring(), Variable(target))
  targetFactors += target -> targetFactor
}
```
This is the only place in the entire code base that makes use of `BoundsSumProductSemiring`, which is to say that `BoundsSumProductSemiring` is not used at all! It's surprising that this doesn't fail `LazyVETest`, though it appears that `LazyVETest` runs fine only because in all of the tests we have, none of the factors passed to this method ever contain more than one variable.

Related to this is the fact that the `Factor.convert` method is never used. Is there any reason to keep it? Right now its functionality is virtually the same as the `createFactor` method, which is to say is creates a new empty factor with the same variables.

Lastly, there is a potential problem with the `BasicFactor.combination` method. Here are the first few lines:
```
override def combination(
  that: Factor[T],
  op: (T, T) => T): Factor[T] = {
  that match {
    case _:SparseFactor[T] => that.combination(this, op)
```
This seems to assume that `op` is commutative, but this is not always the case. BP code in particular uses division here. Fortunately, this has an easy solution: change the last part to `that.combination(this, (a,b) => op(b,a))`, which reverses the order of the arguments to `op`.

**Comment by gtakata** [comment]
I agree with most of this, especially fixing combine.

WRT convert:

The function is mainly to change the type of the factor. For most factors this is not used since they are always Double. However, in some semirings, like SufficientStatisticsSemiring and SumProductUtilitySemiring the type is actually a tuple and not simply a Double. In SufficientStatisticsSemiring the tuple includes a Map and a Seq.

In theory, the factor contents should also be updated to the new type. This is actually done in the function mapTo, which takes a function to convert the old value to the new value and applies it to all the content values, producing a new factor. Note that the type may also be changed in the process (to the type of the semiring).

The solution would seem to be to remove convert and use mapTo instead, so that the factor is appropriately modified when the semiring changes.

We should also review the use of semirings with compound types, eg tuples. Maybe there is a better way, eg MarginalMap.

*******************
Glenn Takata, PhD
Sr Software Engineer
Charles River Analytics
617.491.3474 x625
ww.cra.com

**Comment by bruttenberg** [comment]
William, I think there are three things to do here:


1.       Remove convert and change any occurrences of it to create

2.       Fix the combination

3.       Go through the factor code and made the use of semirings consistent. Unless someone objects, I think every function in the factor should take a semiring as a parameter that defaults to the semiring of the factor. I think the semiring in the factor should primarily be used to identify the type of data in the factor, and only be used to perform arithmetic on the factor when no semiring is passed in.

Does this make sense?

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by gtakata** [comment]
Is there any reason to keep mapTo? It seems that for even the simplest type, eg log prob, you create the factor that way initially rather than convert it from something else. Unless the SufficientStatistics or Utility semirings can’t do it for themselves.

*******************
Glenn Takata, PhD
Sr Software Engineer
Charles River Analytics
617.491.3474 x625
ww.cra.com

**Comment by bruttenberg** [comment]
I would say keep mapTo, since it is mapping between different types T and U. I believe the utility factors do use it.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by wkretschmer** [comment]
Will do. Note that the semiring supplied to `marginalizeTo` cannot be made optional, because according to the compiler "a parameter section with a `*'-parameter is not allowed to have default arguments". So, something like this is not allowed:
```
def marginalizeTo(_semiring: Semiring[T] = semiring, targets: Variable[_]*): Factor[T]
```
It might make sense to take targets as a `List[Variable[_]]` instead.

Another important question is whether the returned factor should be assigned the optional semiring given, or the semiring assigned to this factor. I can see how using the optional semiring might lead to less confision. However, this would also require `Factor.combination` to take in an optional semiring, even though the semiring is never used for computation (i.e. it is just used to construct the resulting factor). Moreover, there are situations where keeping the assigned semiring is desirable. In the case of marginal MAP BP for example, any time we use max-product, we immediately want to switch back to sum-product, and so it would be simpler to keep the assigned sum-product semiring. Which convention has the most compelling arguments in its favor?

This also suggests that a method that returns a new factor of the same type with the same contents and different semiring might be useful. Perhaps we could repurpose `Factor.convert` for this?

**Comment by gtakata** [comment]
I’m not sure if it will work, but you could try currying, eg def marginalizeTo(targets: Variable[_]*)(semiring: Semiring[T] =…)

*******************
Glenn Takata, PhD
Sr Software Engineer
Charles River Analytics
617.491.3474 x625
ww.cra.com

**Comment by wkretschmer** [comment]
Currying works if you're willing to call this with an additional set of parentheses at the end, e.g. `marginalizeTo(target1, target2)()`. You can fix this if you make the semiring implicit: 
`def marginalizeTo(targets: Variable[_]*)(implicit _semiring: Semiring[T] = semiring): Factor[T]`, but personally I don't like these solutions any more than avoiding variable arguments.

**Comment by bruttenberg** [comment]
Let’s try talking about this at tomorrow’s meetings. William, can you just make a list of the different issues and possible solutions?

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>
