### ISSUE TITLE
Online EM doesn't support learned variable defined with If

### ISSUE THREAD

**Issue by guyyos** [p2t2/figaro#594]
hi,
first I would like to thank you for writing this awesome library. I would like to incorporate it in our production code. 
I  would like to model user journeys as hidden markov models (or dbns). But it needs to work in scale, therefore I tried to work with Online EM training algorithm on a toy Markov chain. But it doesn't seem to learn the parameter that is defined with If statement : see below 'confident(1)' .

********************************************************************** code: 

```

import com.cra.figaro.algorithm.factored.VariableElimination
import com.cra.figaro.algorithm.learning.{EMWithBP, EMWithImportance, EMWithMH, EMWithVE}
import com.cra.figaro.language.{Flip, NamedEvidence, Observation, _}
import com.cra.figaro.library.atomic.continuous.Beta
import com.cra.figaro.library.compound.If
import com.cra.figaro.patterns.learning.{ModelParameters, ParameterCollection}


object MCWithOnlineEM {
  val params = ModelParameters()
  val sample_len = 2

  val ini_conf_prob = Beta(2, 2)("ini_conf_prob", params)
  val trans_conf_conf_prob = Beta(2, 2)("trans_conf_conf_prob", params)
  val trans_noconf_conf_prob = Beta(2, 2)("trans_noconf_conf_prob", params)

  class McModel(length: Int, paramCollection: ParameterCollection, modelUniverse: Universe) {
    val confident: Array[Element[Boolean]] = Array.fill(length)(Constant(false))

    val ini_conf_prob = paramCollection.get("ini_conf_prob")
    val trans_conf_conf_prob = paramCollection.get("trans_conf_conf_prob")
    val trans_noconf_conf_prob = paramCollection.get("trans_noconf_conf_prob")

    confident(0) = Flip(ini_conf_prob)("confident" + 0, modelUniverse)
    val tccp = Flip(trans_conf_conf_prob)
    val tnccp = Flip(trans_noconf_conf_prob)
    confident(1) = If(confident(0),tccp,tnccp)("confident" + 1, modelUniverse)
  }

  def f = () => {
    val modelUniverse = new Universe
    new McModel(sample_len, params.priorParameters, modelUniverse)
    modelUniverse
  }

  def main(args: Array[String]): Unit = {
    val em = EMWithVE.online(f, params)
    em.start()
    println("before learning")
    print_res(params)

    val num_samples = 5
    for{ i <- 0 until num_samples}{
      println("**********************   sample = "+i)

      val iniev = List(NamedEvidence("confident" + 0, Observation(true)))
      val ev1 = for{ j <- 1 until sample_len } yield NamedEvidence("confident" + j, Observation(true))
      em.update(iniev++ev1)

      println("after learning")
      print_res(params)

      val futureUniverse1 = Universe.createNew()
      val futureModel1 = new McModel(sample_len, params.posteriorParameters, futureUniverse1)

      for { minute <- 0 until sample_len } {
        println("Probability of confident in time:"+minute+"  = " + VariableElimination.probability(futureModel1.confident(minute), true))
      }

    }
  }

  def print_res(params:ModelParameters) = {

    println("posteriors --")

    println("ini_conf_prob = "+params.posteriorParameters.get("ini_conf_prob"))
    println("trans_conf_conf_prob = "+params.posteriorParameters.get("trans_conf_conf_prob"))
    println("trans_noconf_conf_prob = "+params.posteriorParameters.get("trans_noconf_conf_prob"))
  }
}
 
```

********************************************************************** output : 
**********************   sample = 4
after learning
posteriors --
ini_conf_prob = 0.8571428571428571
trans_conf_conf_prob = 0.5
trans_noconf_conf_prob = 0.5
Probability of confident in time:0  = 0.8571428571428571
Probability of confident in time:1  = 0.5

**Comment by mhoward2718** [comment]
Hello.

This will work if you place explicitly place the `tccp` and `tnccp` elements in the model universe, e.g.:
```scala
    val tccp = Flip(trans_conf_conf_prob)("tccp" + 1, modelUniverse)
    val tnccp = Flip(trans_noconf_conf_prob)("tnccp" + 1, modelUniverse)
```

You could also resolve it by changing the function `f` to use `Universe.createNew()` instead of `new Universe`:

```scala
  def f = () => {
    val modelUniverse = Universe.createNew()
    new McModel(sample_len, params.priorParameters, modelUniverse)
    modelUniverse
  }
```

Here is the explanation for what's going on - When you do things like dynamic models or online EM, then it becomes necessary to explicitly place elements in certain universes.. But typically, a user doesn't need to worry about universes at all in their model.  So, to make the general case easier to write, under the hood there is a default universe that elements implicitly use. When you call `Universe.createNew()`, it changes the default universe to the one that was just created. When you use `... = new Universe`.the default stays the same. So, in your original `McModel`, the outcomes of the `If` were still being created in the initial universe.

My suggestion when using dynamic models or online EM is to explicitly specify which universe elements should be placed in. It helps to avoid any confusion with defaults and implicits.

Thanks for showing interest in Figaro. It is nice to hear that it is being considered for use in production code.

**Comment by guyyos** [comment]
thanks a lot! this works.
In the previous version of my code I actually had this line 

`
confident(1) = If(confident(0),Flip(trans_conf_conf_prob),Flip(trans_noconf_conf_prob))("confident" + 1, modelUniverse)
`
and this didn't work either. I guess that's because you create a variable for every Flip and put it in the default Universe. This could be confusing. 
Anyway I'll use the `Universe.createNew()` which is safer. Thanks
