### ISSUE TITLE
LSFI: Don't reuse subproblem solution if it's a recursion

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#647]
Only reuse solutions if they have already been completed.

**Comment by wkretschmer** [comment]
Is there a clever way to do this while still still taking only constant time to expand a subproblem? The recursion could be indirect (e.g. subproblem A uses subproblem B, and subproblem B uses subproblem A), so you essentially have to backtrack up the whole subproblem graph. Or maybe I shouldn't worry about it because this cost will probably be small anyways.

**Comment by apfeffer** [comment]
If you’re using a depth-first strategy, you can mark a subproblem as open when it gets created and closed when it gets solved. Then, if you find yourself in a subproblem that’s already open, you know it’s a recursion.

**Comment by wkretschmer** [comment]
We need to revisit this issue; my solution does not work. The idea was essentially what Avi described: when expanding with a depth-first strategy, mark a subproblem as open until expansion of that subproblem is complete to the desired depth.

Here's a simple example where this fails. Suppose the top-level problem T directly uses two subproblems A and B. Suppose also that B directly uses A, and A directly uses B. We can expand to a depth of 1 just fine: the expanded subproblem graph is T -> {A,B}, A -> {}, B -> {}. However, expanding to depth 2 breaks the model. We add B as a subproblem of A and add A as a subproblem of B. Marking subproblems as open while expanding doesn't stop either of these steps because when adding B to A, the only open subproblem is A, and when adding A to B, the only open subproblem is B. The resulting subproblem graph is T -> {A,B}, A -> {B}, B -> {A}, which is ill-defined because it contains a cycle. Inference later crashes with a StackOverflowError.

Can one avoid any of this without a global data structure to detect cycles?

**Comment by apfeffer** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1498068212/e74138296a56547dcb2f1ea7c28a0a53/2/e51d88f8b33b1071f12df3e3a5852c07/bc04a8faac0f5134193751c06e7fc466/9efab2399c7c560b34de477b9aa0a465/newton.gif]
Sorry, I don't understand the problem. After you expand to T -> {A,B}, A -> {B}, B -> {A}, you won't subsequently add A to B because A is open, and likewise for adding B to A. So the recursion should terminate. What am I missing?

++++++++++++++++++++++
Dr. Avi Pfeffer
Chief Scientist
Charles River Analytics, Inc.
(617) 491-3474x513
apfeffer@cra.com
www.cra.com


On Wed, Jun 21, 2017 at 1:09 PM, William Kretschmer <notifications@github.com> wrote:

We need to revisit this issue; my solution does not work. The idea was essentially what Avi described: when expanding with a depth-first strategy, mark a subproblem as open until expansion of that subproblem is complete to the desired depth.

Here's a simple example where this fails. Suppose the top-level problem T directly uses two subproblems A and B. Suppose also that B directly uses A, and A directly uses B. We can expand to a depth of 1 just fine: the expanded subproblem graph is T -> {A,B}, A -> {}, B -> {}. However, expanding to depth 2 breaks the model. We add B as a subproblem of A and add A as a subproblem of B. Marking subproblems as open while expanding doesn't stop either of these steps because when adding B to A, the only open subproblem is A, and when adding A to B, the only open subproblem is B. The resulting subproblem graph is T -> {A,B}, A -> {B}, B -> {A}, which is ill-defined because it contains a cycle. Inference later crashes with a StackOverflowError.

Can one avoid any of this without a global data structure to detect cycles?

-

**Comment by wkretschmer** [comment]
After expanding to depth 1, we have T -> {A,B}, A -> {}, B -> {}. Nothing wrong here. We start expanding to depth 2 from the top level. Without loss of generality, we first enter subproblem A, marking it as open. We expand subproblem B from subproblem A. This puts us at depth 2, so we don't recurse on B, and instead turn around in our depth-first search. On the way back up, we mark A as closed. Then, we enter subproblem B from the top level, marking it as open. We expand subproblem A from subproblem B because A is not marked open. Expansion stops again because we're at depth 2 from the top level, so we mark A as closed and return. At this point, we have T -> {A,B}, A -> {B}, B -> {A}, which is wrong. The only way I see to avoid this is to explicitly verify when expanding A from B that B is never used (indirectly) as a subproblem of A.

**Comment by apfeffer** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1498071900/e74138296a56547dcb2f1ea7c28a0a53/2/e51d88f8b33b1071f12df3e3a5852c07/d9da7675dfa5abd9724e661ba9fbcb20/9efab2399c7c560b34de477b9aa0a465/newton.gif]
> At this point, we have T -> {A,B}, A -> {B}, B -> {A}, which is wrong.

Why is this wrong? I don't follow. It seems right to me.

++++++++++++++++++++++
Dr. Avi Pfeffer
Chief Scientist
Charles River Analytics, Inc.
(617) 491-3474x513
apfeffer@cra.com
www.cra.com


On Wed, Jun 21, 2017 at 2:48 PM, William Kretschmer <notifications@github.com> wrote:

After expanding to depth 1, we have T -> {A,B}, A -> {}, B -> {}. Nothing wrong here. We start expanding to depth 2 from the top level. Without loss of generality, we first enter subproblem A, marking it as open. We expand subproblem B from subproblem A. This puts us at depth 2, so we don't recurse on B, and instead turn around in our depth-first search. On the way back up, we mark A as closed. Then, we enter subproblem B from the top level, marking it as open. We expand subproblem A from subproblem B because A is not marked open. Expansion stops again because we're at depth 2 from the top level, so we mark A as closed and return. At this point, we have T -> {A,B}, A -> {B}, B -> {A}, which is wrong. The only way I see to avoid this is to explicitly verify when expanding A from B that B is never used (indirectly) as a subproblem of A.

-

**Comment by wkretschmer** [comment]
Strictly speaking it's correct, but is impossible to perform inference because a subproblem contains itself. Instead, we have to create copies of A or B in these recursive parts.

**Comment by apfeffer** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1498090260/e74138296a56547dcb2f1ea7c28a0a53/2/e51d88f8b33b1071f12df3e3a5852c07/dc2b1869883d66ecb439405e04513e96/9efab2399c7c560b34de477b9aa0a465/newton.gif]
I still don't understand. In T -> {A,B}, A -> {B}, B -> {A}, there are no subproblems that contain themselves. There are two subproblems that mutually contain each other (at different depths), but each can be solved separately. What am I missing?

++++++++++++++++++++++
Dr. Avi Pfeffer
Chief Scientist
Charles River Analytics, Inc.
(617) 491-3474x513
apfeffer@cra.com
www.cra.com


On Wed, Jun 21, 2017 at 3:07 PM, William Kretschmer <notifications@github.com> wrote:

Strictly speaking it's correct, but is impossible to perform inference because a subproblem contains itself. Instead, we have to create copies of A or B in these recursive parts.

-

**Comment by wkretschmer** [comment]
There's no way to resolve a cyclic dependency in subproblems: solving a problem requires solving all of its subproblems first. Solving A requires solving B first, but solving B requires solving A first. Put another way, the set of dependencies between problems in any dynamic programming instance is always a directed acyclic graph.

**Comment by apfeffer** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1498144014/e74138296a56547dcb2f1ea7c28a0a53/2/e51d88f8b33b1071f12df3e3a5852c07/769b2b919ede449bb5abe4a89a24fa73/9efab2399c7c560b34de477b9aa0a465/newton.gif]
But solving A at depth 1 requires solving B at depth 0, and likewise solving B at depth 1 requires solving A at depth 0. So we can, for example:
- Expand A at depth 1
- Expand B at depth 0
- Solve B at depth 0
- Solve A at depth 1
- Expand B at depth 1
- Reuse the depth 1 solution of A we've already computed (since it subsumes depth 0)
- Solve B at depth 1

Why wouldn't this work?

++++++++++++++++++++++
Dr. Avi Pfeffer
Chief Scientist
Charles River Analytics, Inc.
(617) 491-3474x513
apfeffer@cra.com
www.cra.com


On Wed, Jun 21, 2017 at 8:19 PM, William Kretschmer <notifications@github.com> wrote:

There's no way to resolve a cyclic dependency in subproblems: solving a problem requires solving all of its subproblems first. Solving A requires solving B first, but solving B requires solving A first. Put another way, the set of dependencies between problems in any dynamic programming instance is always a directed acyclic graph.

-

**Comment by wkretschmer** [comment]
Ah, if one adds the notion of depth to _solving_, then perhaps it is possible to solve a problem that contains itself, even directly. I suppose it just returns the empty solution when it gets to the end of the recursion, but I haven't quite convinced myself that this produces correct answers. My only concern is that this might not behave well when infinite ranges are involved, since then the range can change at every depth. I'll have to think about this more.

**Comment by wkretschmer** [comment]
Yes, it seems to me that this can't work when the range changes through expansion. We can subsume a "depth 0" solution with a "depth 1" solution because the range could be augmented through expansion.

Nevertheless, perhaps this brings up some questions regarding the process of LSFI. Currently the pattern is to perform some series of refinements on the problem graph, then to solve the problem graph depth-first starting at the top-level. In other words, refining and solving are separate. We made this design choice explicitly for LSFI. As I mentioned, the way we currently deal with recursion is to create a new NestedProblem instance with the same expand function when a subproblem is expanded directly or indirectly inside of itself. This works; it's just that our function to detect recursion is bugged. But it seems your suggestion is to instead interleave refining and solving, which offers an alternative way to solve some recursive problems. It's unclear to me if there's a more general solution, particularly because we don't have the ability to detect the structure of the entire model beforehand. There are also some other weird edge cases: what happens when a self-nested problem uses a global inside of itself?

The other option is always to disallow Chain function memoization inside a recursion.
