### ISSUE TITLE
Merge particle states in particleFilter

### ISSUE THREAD

**Issue by saurabhjha1** [p2t2/figaro#654]
Hi, 

I am trying to use `ParticleFilter` to compute the distribution of a variable of type `ABC` (described below. I want to understand how to merge samples/particles in the `ParticleFilter` when the samples/particles are custom classes and not scala data types. 

For example, I have a custom class
```
class ABC(val name: MyNameClass, val weight: Double){
      override def equals(o: scala: Any) : Boolean = {.....}
}
```

I would like to merge the particles with same `name` and sum the weights corresponding weights to produce a new particle. Figaro is not able to do this. The output of `computeCurrentDistribution` and converting to `List` looks something like this

```
(0.1, (s = s1, w= 0.01)), (0.2, (s = s1, w=0.02)), (0.1, (s = s2, w -0.00043))
```

Thanks
Saurabh

**Comment by bruttenberg** [comment]
Hi Sauragh,

Figaro can do this. I think the problem is that in Scala, class equality is defined by the equals function and hashCode function. So if you want to have two classes with the same name/weight be considered equivalent, you need to have equals == true and hashCode == true.

An alternative is to just declare class ABS as a case class, and that will take care of it for you.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by saurabhjha1** [comment]
Thanks for your immediate response. This solves the problem.
