### ISSUE TITLE
Loopy PGMs in Figaro

### ISSUE THREAD

**Issue by ssbanerje** [p2t2/figaro#655]
How does one create loopy PGMs in Figaro? It seems that how the `Apply`/`Chain` functions are setup, they can only be applied in situations that the inputs of an `Apply` are computed before it is computed. This cannot hold for loopy PGMs.

Is there an example for creating a loopy PGM?

**Comment by bruttenberg** [comment]
Can you clarify what you mean by a PGM with looks? In the sense of a directed cyclic graph? Or something else?

If you are talking about directed cyclic graphs, Figaro does not support it, at least not natively. You might be able to create one using lazy variables in Scala, but I’m not sure.

Figaro does support recursive models which may suffice for your needs.

Brian

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by ssbanerje** [comment]
I meant a Factor Graph (undirected) that has a loop. Something like this (darkened = factor, other = variable)

```
          Λ        ┌──┐             Λ       
         ╱■╲       │  │            ╱■╲      
  ┌─────▕■■■▏──────│  │───────────▕■■■▏───┐ 
  │      ╲■╱       └──┘            ╲■╱    │ 
  │       V                         V     │ 
  │                                       │ 
  │                                       │ 
  │                                       │ 
  │                                       │ 
  │                                       │ 
  │                                       │ 
  │                                       │ 
  │                                       │ 
  │                                       │ 
┌──┐                 Λ                  ┌──┐
│  │                ╱■╲                 │  │
│  │   ────────────▕■■■▏────────────────│  │
└──┘                ╲■╱                 └──┘
                     V                      
```

**Comment by bruttenberg** [comment]
Hi Subho,

Since Figaro is a generative language, the user doesn’t explicitly build factor graphs, they get compiled from the model description. There are various ways of writing a Figaro model that will compile down into a loopy factor graph. For example, creating an undirected model like this:

val a = Uniform(1, 2, 3)
val b = Uniform(2, 3, 4)
val c = Uniform(3, 4, 5)
val ab = a === b
val bc = b === c
val ca = c === a

Should create a loopy factor graph.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>
