### ISSUE TITLE
Bounds check in ConstraintFactory

### ISSUE THREAD

**Issue by wkretschmer** [p2t2/figaro#661]
We previously printed a warning in the Element class when a constraint value was not in the range [0,1], because this violates an assumption needed for lazy factored inference. We removed the warning in [this commit](https://github.com/p2t2/figaro/commit/a91f640055958fe94244795cbb376a12581fc150). Instead, we should have an exception-throwing check for this case in ConstraintFactory. Of course, we only need this check if the range of a variable includes star.

**Comment by apfeffer** [comment]
Actually, it’s not just if the range includes *. This exception should be thrown any time LSFI is used. The reason is that we cannot guarantee the correctness of the algorithm unless all constraint values are in [0, 1]. What if the element value that violates this is in some embedded subproblem that hasn’t been expanded?

**Comment by wkretschmer** [comment]
You're right, not having star in the range does not guarantee that the variable's range will not contain star at any future point. Instead, this should check if the variable is fully _enumerated_, which is something LSFI can keep track of.

**Comment by apfeffer** [comment]
I think lazy VE should be deprecated when we release LSFI.
