### ISSUE TITLE
Cross build for scala 2.12

### ISSUE THREAD

**Issue by francisdb** [p2t2/figaro#665]
This is the state on April 25 2017

Tried building master with 2.12 and these dependencies were missing because of older versions that have not been built for 2.12 or no new version compiled against 2.12 available

| dep                | status             | link  |
| ------------- | ------------- | ----- |
| breeze | 0.13 | [maven central](http://repo1.maven.org/maven2/org/scalanlp/breeze_2.12/0.13/) |
| argonaut | 6.2 | [maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.argonaut%22%20AND%20a%3A%22argonaut_2.12%22) |
| scala-swing | 2.0.0 | [maven central](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22scala-swing_2.12%22) |
|scalatest| ok | [maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.scalatest%22%20AND%20a%3A%22scalatest_2.12%22) |
|scoverage| ok | [maven central](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22scalac-scoverage-plugin_2.12%22)|
|scalameter|ok|[maven central](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22scalameter_2.12%22)|
|akka|ok|[maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.typesafe.akka%22%20AND%20a%3A%22akka-actor_2.12%22)|

**Comment by mreposa** [comment]
We are discussing the support of Scala 2.12 for the next Figaro release.

**Comment by francisdb** [comment]
4.1 or 4.2 milestone?

**Comment by mreposa** [comment]
After Figaro 4.1 is released

**Comment by francisdb** [comment]
Anything I can do to make sure that does not take another 10 months?

**Comment by apfeffer** [comment]
We’re actually hoping to release 4.2 fairly soon after 4.1. We have some significant algorithmic work that needs some more refining and testing that will be released in 4.2. But we also don’t want that to hold up releasing some useful improvements we’ve made recently, which is why we’re releasing 4.1 first. We’re very close to releasing 4.1 and I don’t want to hold that up by migrating to the new version of Scala. We’ll do that after the release and make sure it’s included in the next release. So hopefully not another 10 months!

If you can help us with the migration, that would be appreciated.

**Comment by francisdb** [comment]
Thanks, might have a go at it.

**Comment by francisdb** [comment]
updated the ticket with a table of dependencies and their state regarding 2.12
the only blocking one is breeze which should be released soon

as for the rc/milestone versions those should probably be final before actually releasing a 2.12 figaro?

**Comment by refried** [comment]
breeze has been released as of Jan 8: http://repo1.maven.org/maven2/org/scalanlp/breeze_2.12/0.13/

**Comment by francisdb** [comment]
all RC versions have also been released as final so nothing left to wait for

**Comment by francisdb** [comment]
ping 🛎

**Comment by francisdb** [comment]
Looks like there is already a pull request for this one by @paulp https://github.com/p2t2/figaro/pull/700

**Comment by mreposa** [comment]
Yes but unfortunately it was done against master, which has already been released.

**Comment by paulp** [comment]
Ok, what should it be against?

**Comment by mreposa** [comment]
The latest development branch is DEV4.2

**Comment by paulp** [comment]
FYI, you can make this more apparent to outsiders in the future by pointing the remote head at that branch (e.g. `git remote set-head origin DEV4.2`)

**Comment by paulp** [comment]
For the record I reworked the 2.12 PR https://github.com/p2t2/figaro/pull/705 against DEV4.2 as indicated back on May 23, but it has not received any attention and now is in conflict. Since it's an uncreative port to the current release version of scala, it should have been straightforward to merge. I don't intend to fix the conflicts given that I have no inkling of whether it will ever be accepted. It's discouraging when even the pull requests which are utterly without controversy have to take up residence in pull request limbo.

**Comment by francisdb** [comment]
We are also waiting for this to be merged. And since cross building is rather trivial I see no reason for not accepting this PR.

**Comment by paulp** [comment]
Yet more for the record: I object to having my work extracted from the pull request and applied without any credit, as was [done](https://github.com/p2t2/figaro/pull/705) on July 26th, and my request to remedy it ignored. This ends my interest in figaro.

**Comment by apfeffer** [comment]
Paul,

Sorry, I was just about to send a message to the list.

You make a good point that contributors deserve to be acknowledged. We have gone back through the records and listed all the contributors in each of the files to which they have contributed. I'm sorry that the pull request wasn't handled in the right way.

Avi

++++++++++++++++++++++
Dr. Avi Pfeffer
Chief Scientist
Charles River Analytics, Inc.
(617) 491-3474x513
apfeffer@cra.com
www.cra.com


On Sun, Aug 20, 2017 at 1:44 AM, Paul Phillips <notifications@github.com> wrote:

Yet more for the record: I object to having my work extracted from the pull request and applied without any credit, as was done<https://github.com/p2t2/figaro/pull/705> on July 26th, and my request to remedy it ignored. This ends my interest in figaro.

-

**Comment by francisdb** [comment]
https://github.com/p2t2/figaro/releases/tag/5.0.0.0
