### ISSUE TITLE
Create a CPD from a list of parents of the same type

### ISSUE THREAD

**Issue by davidhamblin** [p2t2/figaro#730]
Many of the structures within Figaro support only 1 to 5 prior probabilities with any type, such as CPD, RichCPD, Apply, and Tuple. Would it be possible, if the type is consistent, to allow the use of a sequence/list for input of the same type? Instead of something like (T1, T2, T3) input into a CPD, you'd have Seq[T] or List[T]. This would allow for much bigger Bayesian networks that use consistent types (like names of states), such as Symbol or String.

**Comment by bruttenberg** [comment]
Hi David,

As you point out, because of typing reasons we were never able to make elements that support generic, unlimited priors. You do have two options:


1.       You can always nest elements if you need more than 5 in say, an Apply. It works but I admit it’s cumbersome.

2.       You can always check out the collections library. This library lets you use scala-like collection operations on elements. So you can do things like put a set of elements into a collection, and fold them all into a single element over lists, which you can then use as the prior for another variable.

Does this help?

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by davidhamblin** [comment]
Interesting, I'll have to take a look at your suggestions, thank you for the quick response! As an aside, do you think it is at all possible to implement an element that would take any number of priors -- as long as they possess the same type (and not saying that CRA needs to do it)? I have been experimenting with it locally, but I am unfortunately limited by my knowledge of the package and Scala.

**Comment by bruttenberg** [comment]
No problem.

To answer your question, yes I think it is possible. If I were doing it, the quick and dirty way would be to put some syntactic sugar around my suggestion of using a collection. A more optimal way do it would be to create an element that takes in a variable argument number of elements and compose them internally into a data structure that say, a chain, could then use.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by davidhamblin** [comment]
Brian,

I've locally implemented a new form of CPD that takes a List[T] for priors and clauses, which included adding a new CPDList class to CPD.scala, new ApplyList function to Apply.scala, apply function in Tuple.scala, a case in LazyValues.scala, and a makeFactors constructor in ApplyFactory.scala. This should allow for any number of priors, given that they are of the same type. So far I've tested it against the Figaro implementations of CPD1, CPD2, and CPD3. It seems to suit my purposes, but would you be interested in this code at all?

**Comment by bruttenberg** [comment]
Hi David,

I think we'd definitely be interested in that. Do you have it in a branch we can look at?

**Comment by davidhamblin** [comment]
Certainly, you can find it on the branch david-fork/master at https://github.com/davidhamblin/figaro/tree/david-fork/master 

There are two commits, one with the majority of the code and the second with a small name change (I started with Seq and changed to List in development). The commit with the implementation is https://github.com/davidhamblin/figaro/commit/19735d1015f83e846e148f139ba706cb6362de59

I have tested the code myself against the implementations of CPD1 through 5, as well as one with 6 priors using a separate program for building Bayesian networks by hand, using VariableElimination to test accuracy, but did not add any tests to the branch itself.
